version: "3.3"

services:
  backend:
    build: ./stasshdev/noteorganizer-backend
    environment:
      JWT_SECRET: ${JWT_SECRET}
    container_name: backend
    working_dir: /backend
    command: node server/index.js
    ports:
      - "5000:5000"
  

  frontend:
    build: ./stasshdev/noteorganizer-frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend